# This profile is for local testing
---
__use_yte__: true
__definitions__:
  - from tempfile import mkdtemp
  - tmpdir = mkdtemp()
resources:
  - concurrent_busco_downloads=1
  - concurrent_storage_uploads=1
restart-times: 0
local-cores: 2
cores: 50
latency-wait: 60
jobs: 128
keep-going: true
keep-storage-local-copies: true
rerun-incomplete: true
printshellcmds: true
use-singularity: true
use-conda: False
singularity-args: ?f"-B $PWD,{tmpdir}
  --nv
  -H $(mktemp -d)
  --pwd $PWD
  --containall --cleanenv --writable-tmpfs"
singularity-prefix: $HOME/.apptainer/cache/library
apptainer-prefix: $HOME/.apptainer/cache/library
shadow-prefix: ?tmpdir
# s3
storage-s3-endpoint-url: https://projects.pawsey.org.au
storage-s3-access-key: $AWS_ACCESS_KEY_ID
storage-s3-secret-key: $AWS_SECRET_ACCESS_KEY
