reads_path:
  - "s3://pawsey1132.atol.testassembly/Emblema_pictum_247745/results/reads/hifi/ccs_reads.fasta.gz"
reads_type: "hifi"
reads_layout: "SINGLE"
pacbio_barcode_names: "bc2001,bc2009"
busco_lineages: "passeriformes_odb10"
sample_id: "EmblemaPictum247745"
scientific_name: "Emblema pictum"
taxid: 247745
dimensionality_reduction_methods: ["pca", "random_trees"]
# ok
busco_lineages_folder: "s3://pawsey1132.atol.refdata.busco/busco/lineages"
diamond_uniprot_database_path: "s3://pawsey1132.atol.refdata.uniprot.diamond/diamond/reference_proteomes.dmnd"
ncbi_ranked_lineage_path: "s3://pawsey1132.atol.refdata.v1/taxdump/rankedlineage.dmp"
ncbi_taxonomy_path: "s3://pawsey1132.atol.refdata.v1/taxdump"
nt_database_path: "s3://pawsey1132.atol.refdata.v1/ncbi_nucleotide_blast"
nt_database_prefix: nt
nt_kraken_database_path: "s3://pawsey1132.atol.refdata.kraken/k2_core_nt"
vecscreen_database_path: "s3://pawsey1132.atol.refdata.vecscreen/vecscreen/"
diamond_nr_database_path: "s3://pawsey1132.atol.refdata.nr.diamond/diamond/nr.dmnd"
