reads_path:
  - "s3://pawsey1132.atol.testassembly/Emblema_pictum_247745/results/reads/hifi/ccs_reads.fasta.gz"
reads_type: "hifi"
reads_layout: "SINGLE"
pacbio_barcode_names: "bc2001,bc2009"
busco_lineages: "aves_odb10"
sample_id: "EmblemaPictum247745"
scientific_name: "Emblema pictum"
taxid: 247745
dimensionality_reduction_methods: ["pca", "random_trees"]
nt_database_path: "s3://pawsey1132.atol.refdata.v1/ncbi_nucleotide_blast"
nt_database_prefix: nt
ncbi_taxonomy_path: "s3://pawsey1132.atol.refdata.v0/taxdump"
ncbi_ranked_lineage_path: "s3://pawsey1132.atol.refdata.v0/taxdump/rankedlineage.dmp"
busco_lineages_folder: "s3://pawsey1132.atol.refdata.v0/busco/lineages"
nt_kraken_database_path: "s3://pawsey1132.atol.refdata.v0/kraken2_nt"
diamond_nr_database_path: "s3://pawsey1132.atol.refdata.v0/diamond/reference_proteomes.dmnd"
diamond_uniprot_database_path: "s3://pawsey1132.atol.refdata.v0/uniprot_reference_proteomes/FIXME.dmnd"
vecscreen_database_path: "s3://pawsey1132.atol.refdata.v0/FIXME"
