dataset_id: 350730_AusARG
# output_prefix: "s3://pawsey1132.atol.testpostassembly"
output_prefix: "fs://test/results"
containers:
  bbmap:
    prefix: docker
    url: quay.io/biocontainers/bbmap
    tag: 39.13--he5f24ec_1
  samtools:
    prefix: docker
    url: quay.io/biocontainers/samtools
    tag: 1.21--h96c455f_1
  pigz:
    prefix: docker
    url: quay.io/biocontainers/pigz
    tag: "2.8"
  ncbi-datasets-pylib:
    prefix: docker
    url: quay.io/biocontainers/ncbi-datasets-pylib
    tag: 16.6.1--pyhdfd78af_0
